---
title: "Modelos de regresión"
output: 
  prettydoc::html_pretty:
    theme: leonids
    fig_caption: yes
    highlight: tango
    toc: yes
---
Renuncia de responsibilidad.

# Regresión lineal simple
Objetivo: construir un modelo tal que $Y_i = \beta_0 + \beta_1\cdot X_i + \epsilon_i$

```{r include = FALSE}
data("iris")
var.endogena <- iris[,1]
var.explicativa <- iris[,2]
datos <- data.frame(cbind(var.endogena, var.explicativa))
library(DAAG)
library(stats)
```


## Construcción del modelo
```{r}
ajuste <- lm(var.endogena~var.explicativa, data = datos)

coeficientes <- ajuste$coefficients
valores.ajustados <- ajuste$fitted.values
residuos <- ajuste$residuals
gl.residuos <- ajuste$df.residual # grados de libertad de los residuos
gl.modelo <- ajuste$rank          # grados de libertad del modelo
SSR <- sum(residuos^2)            # suma de residuos al cuadrado
MSSR <- SSR/gl.residuos           # media de SSR
leverage <- hatvalues(ajuste)
n.equivalente.datos <- 1/leverage
```

## Inferencia
### Intervalos de confianza
```{r}
intervalo.parametros <- confint(ajuste, level = 0.95)
intervalo.varianza <- gl.residuos * MSSR / qchisq(p=0.10,df=gl.residuos)
```
### Contrastes de hipótesis
```{r}
# Contraste de regresión (H_0: beta_1 = 0):
resumen <- summary(ajuste)
contraste <- resumen$coefficients
# en la última columna tenemos el contraste de regrsión y el contraste de
# beta_0 = 0

# Podemos acceder al resultado del mismo contraste mediante anova:
contraste.regresion <- anova(ajuste)
```

## Bondad del ajuste
```{r results = 'hide'}
# Coeficiente de correlación lineal de Pearson estimado:
r <- cor(var.endogena, var.explicativa)
# ¿Es significativamente diferente de cero? H0:rho=0 vs H1:rho!=0
cor.test(var.endogena, var.explicativa, method = "pearson")

# Coeficiente de determinación
R2 <- resumen$r.squared
R2.ajustado <- resumen$adj.r.squared

# AIC, Criterio de Información de Akaike
AIC(ajuste)    # cuanto más pequeño, mejor (más ajustado)
# BIC, Criterio de Información Bayesiano (lo mismo, pero teniendo en cuenta
# el número de datos que tenemos)
BIC(ajuste)    # cuanto más pequeño, mejor (más ajustado)

# Validación cruzada
cvRes <- DAAG::CVlm(data=datos, form.lm=var.endogena~var.explicativa,
                    m=5, dots=FALSE, seed=29, plotit="Observed", 
                    legend.pos="topleft", 
                    printit = FALSE, main="")
```


## Diagnosis del modelo
## Análisis de influencia
## Predicciones


# Regresión lineal múltiple

# Regresión logística
## prueba
### más pruebas
